In [10]:
import matplotlib
matplotlib.use('PDF')
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib
import seaborn as sns
from scipy.stats import gaussian_kde
from scipy import stats
import statsmodels.api as sm
from matplotlib.backends.backend_pdf import PdfPages

In [2]:
original_df = pd.read_csv('/root/data/BitcoinHeistData.csv') 
Processed_df = pd.read_csv('/root/BTC_BalancedData_Inversed_2.csv')

In [3]:
original_df

,address,year,day,length,weight,count,looped,neighbors,income,label
0,111K8kZAEnJg245r2cM6y9zgJGHZtJPy6,2017,11,18,0.008333,1,0,2,1.000500e+08,princetonCerber
1,1123pJv8jzeFQaCV4w644pzQJzVWay2zcA,2016,132,44,0.000244,1,0,1,1.000000e+08,princetonLocky
2,112536im7hy6wtKbpH1qYDWtTyMRAcA2p7,2016,246,0,1.000000,1,0,2,2.000000e+08,princetonCerber
3,1126eDRw2wqSkWosjTCre8cjjQW8sSeWH7,2016,322,72,0.003906,1,0,2,7.120000e+07,princetonCerber
4,1129TSjKtx65E35GiUo4AYVeyo48twbrGX,2016,238,144,0.072848,456,0,1,2.000000e+08,princetonLocky
...,...,...,...,...,...,...,...,...,...,...
2916692,12D3trgho1vJ4mGtWBRPyHdMJK96TRYSry,2018,330,0,0.111111,1,0,1,1.255809e+09,white
2916693,1P7PputTcVkhXBmXBvSD9MJ3UYPsiou1u2,2018,330,0,1.000000,1,0,1,4.409699e+07,white
2916694,1KYiKJEfdJtap9QX2v9BXJMpz2SfU4pgZw,2018,330,2,12.000000,6,6,35,2.398267e+09,white
2916695,15iPUJsRNZQZHmZZVwmQ63srsmughCXV4a,2018,330,0,0.500000,1,0,1,1.780427e+08,white
2916696,3LFFBxp15h9KSFtaw55np8eP5fv6kdK17e,2018,330,144,0.073972,6800,0,2,1.123500e+08,white

In [4]:
Processed_df

,address,year,day,length,weight,count,looped,neighbors,income,n_address_feature,...,looped_ratio,merge_behavior,length_weight,count_looped,month,week,total_volume,average_volume,transaction_frequency,label
0,1533772,2014,72,144,2.317708,1521,1,2,5.165951e+08,6,...,0.166667,0.001524,333.750001,1521,2,10,2.697488e+09,4.495813e+08,4120,1
1,1776340,2016,168,144,0.134686,3265,0,2,1.199940e+08,1,...,0.000000,0.000041,19.286471,0,5,23,1.199940e+08,1.199940e+08,3265,0
2,1569751,2013,261,100,0.819592,83,0,2,5.107930e+08,21,...,0.000000,0.009954,82.258631,0,8,37,2.533692e+10,1.206497e+09,6004,0
3,2373270,2016,146,52,0.000074,1,0,2,1.136801e+08,4,...,0.000000,0.000074,0.006953,0,4,20,3.779784e+08,9.035609e+07,2335,0
4,607031,2015,203,4,0.055463,2,0,2,2.019773e+08,8,...,0.000000,0.036826,0.221597,0,6,29,2.638680e+09,2.666934e+08,824,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
74799,199862,2015,198,144,0.067782,2195,152,1,1.786569e+08,15,...,10.133333,0.000031,9.760626,333640,6,28,3.557338e+09,2.371558e+08,12708,1
74800,413882,2017,94,28,0.003906,1,0,2,1.000000e+08,1,...,0.000000,0.003906,0.109375,0,3,13,1.000000e+08,1.000000e+08,1,2
74801,442589,2016,75,2,0.250000,1,0,2,5.000000e+07,1,...,0.000000,0.250000,0.500000,0,2,10,5.000000e+07,5.000000e+07,1,2
74802,1742918,2014,94,4,1.000000,1,0,1,2.331068e+08,9,...,0.000000,1.000000,3.553512,0,3,13,2.350172e+09,2.568325e+08,5420,1
74803,790586,2015,160,4,0.403846,9,0,3,4.450000e+08,1,...,0.000000,0.044872,1.615385,0,5,22,4.450000e+08,4.450000e+08,9,1

In [5]:
#Function start here

In [6]:
font = {'size'   : 30}

matplotlib.rc('font', **font)

In [180]:
#Function to show data is balanced
def PercentageCal(df,HeadNum):
    Percentage = 100*(df/df.sum()).sort_values(ascending=False)
    Select = Percentage.head(HeadNum)
    Rest = pd.Series(Percentage.loc[Percentage.index[HeadNum:]].sum(), index = ['Rest'])
    Combined = pd.concat([Select,Rest])
    Org_Select = df[:HeadNum].squeeze()
    Org_Rest = pd.Series(df[HeadNum:].sum(),index = ['Rest'])
    Org_Combined = pd.concat([Org_Select,Org_Rest])
    return Percentage, Select, Rest, Combined, Org_Combined


def pct_value(val):
    def calc_pct(pct):
        absolute = int(pct/100.*np.sum(val))
        return "{:.1f}%\n{:d}".format(pct, absolute)
    return calc_pct

def normalization_plot(df,ax):
    df.hist(ax= ax, bins=30, density=True, alpha=0.5)
    mu, sigma = stats.norm.fit(df)
    x = np.linspace(df.min(), df.max(), 100)
    pdf = stats.norm.pdf(x, mu, sigma)
    ax.plot(x, pdf, 'r-', linewidth=2)

def pie_plot(ax, df, PieHeadNum=5, HeadSelect=False, Plotstitle=''):
    Percentage, Select, Rest, Combined,Org_Combined = PercentageCal(df, PieHeadNum)
    df = df
    pct_label = df
    if HeadSelect == True: 
        df = Combined
        pct_label = Org_Combined
    ax.pie(df, labels=df.index,autopct = pct_value(df))
    ax.set_title(Plotstitle)

In [171]:
def ShowBalaPlots(df,tar_label,Processed = False,figsizeX = 50,figsizeY = 50,Kdedensity = True,ViolinVert = False,ScaAlpha = 0.5):
    
    tar_df = df[tar_label]

    
    # Acquire M, PA, PR, W data
    if (Processed):
        m_df = df.loc[df['label'] == 0,tar_label]
        pa_df = df.loc[df['label'] == 1,tar_label]
        pr_df = df.loc[df['label'] == 2,tar_label]
        w_df = df.loc[df['label'] == 3,tar_label]
    else:
        m_df = df.loc[df['label'].str.startswith("m"),tar_label]
        pa_df = df.loc[df['label'].str.startswith("pa"),tar_label]
        pr_df = df.loc[df['label'].str.startswith("pr"),tar_label]
        w_df = df.loc[df['label'].str.startswith("w"),tar_label]
    
    tar_df_cnt = tar_df.value_counts()    
    m_df_cnt = m_df.value_counts()
    pa_df_cnt = pa_df.value_counts()
    pr_df_cnt = pr_df.value_counts()
    w_df_cnt = w_df.value_counts()
    print(tar_df_cnt)
    print(m_df_cnt)
    print(pa_df_cnt)
    print(pr_df_cnt)
    print(w_df_cnt)
    
    
    
   # Define your filename outside the loop
    filename = 'original ' + tar_label + ' distribution.pdf'
    if Processed:
        filename = 'preprocessed ' + tar_label + ' distribution.pdf'
    
    fixname = filename

    #Start plot figures
    fig, ax =plt.subplots(1,5,figsize = (70,70))
    
    #Pie Chart
    pie_plot(ax[0], tar_df_cnt,HeadSelect = True, PieHeadNum = 2,Plotstitle='Total '+ tar_label+' Distribution')
    pie_plot(ax[1], m_df_cnt,HeadSelect = True, PieHeadNum = 5,Plotstitle='Montreal '+ tar_label+' Distribution')
    pie_plot(ax[2], pa_df_cnt,HeadSelect = True, PieHeadNum = 4,Plotstitle='Panuda '+ tar_label+' Distribution')
    pie_plot(ax[3], pr_df_cnt,HeadSelect = True, PieHeadNum = 8,Plotstitle='Princeton '+ tar_label+' Distribution')
    pie_plot(ax[4], w_df_cnt,HeadSelect = True, PieHeadNum = 2,Plotstitle='White '+ tar_label+' Distribution')
    filename = fixname
    filename = 'Pie Chart ' + filename
    with PdfPages(filename) as pdf:
        pdf.savefig(fig)
    
    #KDE
    fig, ax =plt.subplots(5,1,figsize = (figsizeX,figsizeY))
    tar_df.plot.kde(ax=ax[0],legend = True,label = 'Total ')
    ax[4].set_title('Total Distribution')
    m_df_cnt.plot.kde(ax=ax[1],legend = True,label = 'Montreal ')
    ax[4].set_title('Montreal Data Distribution')
    pa_df_cnt.plot.kde(ax=ax[2],legend = True,label = 'Panuda ')
    ax[4].set_title('Panuda Data Distribution')
    pr_df_cnt.plot.kde(ax=ax[3],legend = True,label = 'Princeton ')
    ax[4].set_title('Princeton Data Distribution')
    w_df_cnt.plot.kde(ax=ax[4],legend = True,label = 'White ')
    ax[4].set_title('White Data Distribution')
    filename = fixname
    filename = 'KDE Chart ' + filename
    with PdfPages(filename) as pdf:
        pdf.savefig(fig)
    #Hist
    fig, ax =plt.subplots(5,1,figsize = (figsizeX,figsizeY))
    tar_df.plot.hist(ax=ax[0],legend = True,density=Kdedensity,label = 'Total ')
    ax[0].set_title('Total Distribution')
    m_df_cnt.plot.hist(ax=ax[1],legend = True,density=Kdedensity,label = 'Montreal ')
    ax[1].set_title('Montreal Data Distribution')
    pa_df_cnt.plot.hist(ax=ax[2],legend = True,density=Kdedensity,label = 'Panuda ')
    ax[2].set_title('Panuda Data Distribution')
    pr_df_cnt.plot.hist(ax=ax[3],legend = True,density=Kdedensity,label = 'Princeton ')
    ax[3].set_title('Princeton Data Distribution')
    w_df_cnt.plot.hist(ax=ax[4],legend = True,density=Kdedensity,label = 'White ')
    ax[4].set_title('White Data Distribution')
    filename = fixname
    filename = 'Hist Plot ' + filename
    with PdfPages(filename) as pdf:
        pdf.savefig(fig)
    #Violin Plot
    fig, ax =plt.subplots(5,1,figsize = (figsizeX,figsizeY))
    ax[0].violinplot(tar_df,vert = ViolinVert)
    ax[0].set_title('Total Distribution')
    ax[1].violinplot(m_df,vert = ViolinVert)
    ax[1].set_title('Montreal Data Distribution')
    ax[2].violinplot(pa_df,vert = ViolinVert)
    ax[2].set_title('Panuda Data Distribution')
    ax[3].violinplot(pr_df,vert = ViolinVert)
    ax[3].set_title('Princeton Data Distribution')
    ax[4].violinplot(w_df,vert = ViolinVert)
    ax[4].set_title('White Data Distribution')
    filename = fixname
    filename = 'Violin Plot ' + filename
    with PdfPages(filename) as pdf:
        pdf.savefig(fig)
        
    #Q-Q Plot
    fig, ax =plt.subplots(5,1,figsize = (figsizeX,figsizeY))
    normalization_plot(tar_df_cnt,ax[0])
    ax[0].set_title('Total Distribution')
    normalization_plot(m_df_cnt,ax[1])
    ax[1].set_title('Total Distribution')
    normalization_plot(pa_df_cnt,ax[2])
    ax[2].set_title('Total Distribution')
    normalization_plot(pr_df_cnt,ax[3])
    ax[3].set_title('Total Distribution')
    normalization_plot(w_df_cnt,ax[4])
    ax[4].set_title('Total Distribution')
    filename = fixname
    filename = 'QQ Plot ' + filename
    with PdfPages(filename) as pdf:
        pdf.savefig(fig)

In [172]:
ShowBalaPlots(original_df,'year')

income
1.000000e+08    73629
5.000000e+07    34234
2.000000e+08    26212
1.000000e+09    16838
3.000000e+07    16088
                ...
4.605623e+07        1
9.571959e+08        1
3.546833e+09        1
2.312033e+08        1
1.780427e+08        1
Name: count, Length: 1866365, dtype: int64
income
1.200000e+08    1818
2.000000e+08     511
1.000000e+08     464
5.000000e+07     334
2.400000e+08     243
                ...
1.021000e+08       1
2.133000e+08       1
2.590859e+09       1
1.862000e+08       1
5.714286e+07       1
Name: count, Length: 7109, dtype: int64
income
1.000000e+08    373
2.000000e+08    264
2.080000e+08    219
5.000000e+07    161
3.000000e+08    109
               ...
3.760792e+08      1
3.039800e+08      1
1.907700e+08      1
1.192229e+08      1
2.517130e+09      1
Name: count, Length: 6935, dtype: int64
income
100000000.0    2810
80000000.0     1589
50000000.0     1424
200000000.0     985
300000000.0     938
               ...
94920000.0        1
505778112.0       1
399985310.0       1
40960000.0        1
149992387.0       1
Name: count, Length: 2700, dtype: int64
income
1.000000e+08    69982
5.000000e+07    32315
2.000000e+08    24452
1.000000e+09    16615
3.000000e+07    15768
                ...
3.361174e+08        1
1.101211e+09        1
1.062017e+08        1
4.302170e+08        1
1.780427e+08        1
Name: count, Length: 1856880, dtype: int64

In [178]:
def PercentageCal(df,HeadNum):
    Percentage = 100*(df/df.sum()).sort_values(ascending=False)
    Select = Percentage.head(HeadNum)
    Rest = pd.Series(Percentage.loc[Percentage.index[HeadNum:]].sum(), index = ['Rest'])
    Combined = pd.concat([Select,Rest])
    Org_Select = df[:HeadNum].squeeze()
    Org_Rest = pd.Series(df[HeadNum:].sum(),index = ['Rest'])
    Org_Combined = pd.concat([Org_Select,Org_Rest])
    return Percentage, Select, Rest, Combined, Org_Combined

In [179]:
PercentageCal(original_df['year'].value_counts(),5)

(year
 2016    13.050070
 2014    12.867946
 2013    12.771090
 2015    12.641046
 2017    12.633674
 2012    12.538635
 2011    12.183268
 2018    11.314271
 Name: count, dtype: float64,
 year
 2016    13.050070
 2014    12.867946
 2013    12.771090
 2015    12.641046
 2017    12.633674
 Name: count, dtype: float64,
 Rest    36.036174
 dtype: float64,
 2016    13.050070
 2014    12.867946
 2013    12.771090
 2015    12.641046
 2017    12.633674
 Rest    36.036174
 dtype: float64,
 2016     380631
 2014     375319
 2013     372494
 2015     368701
 2017     368486
 Rest    1051066
 dtype: int64)

In [175]:
original_df['year'].value_counts()[2016]

380631